QuanLyBanSach-dbf/QuanLyBanSach-dbf/QuanLyBanSach/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using QuanLyBanSach.Data;

namespace QuanLyBanSach.Controllers
{
    public class CartController : Controller
    {
        BookStore db = new BookStore();


        public ActionResult Index()
        {
            return View();
        }

        //        /// <summary>
        //        /// Get an order by id
        //        /// </summary>
        //[HttpGet]
        //public ActionResult GetCart(int? id, int? depth)
        //{
        //    Order yourOrder;
        //    if (id != null)
        //    {
        //        yourOrder = db.Orders.Find(id);
        //        if (yourOrder == null)
        //        {
        //            return null;
        //        }
        //    }
        //    else
        //    {
        //        yourOrder = CheckOrderId();
        //    }

        //    var result = new JsonNetResult
        //    {
        //        Data = yourOrder,
        //        JsonRequestBehavior = JsonRequestBehavior.AllowGet,
        //        Settings = {
        //                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
        //                    MaxDepth = depth ?? 3// order, orderdetail, product
        //                }
        //    };

        //    return result;
        //}

        //#region Customer

        ///// <summary>
        ///// Get a customer by id
        ///// </summary>
        //[HttpGet]
        //public ActionResult GetCustomer(int? id)
        //{
        //    AnonymousUser customer;
        //    if (id != null)
        //    {
        //        customer = db.AnonymousUsers.Find(id);
        //        if (customer == null)
        //        {
        //            return null;
        //        }
        //    }
        //    else
        //    {
        //        customer = CheckCustomerId();
        //    }

        //    var result = new JsonNetResult
        //    {
        //        Data = customer,
        //        JsonRequestBehavior = JsonRequestBehavior.AllowGet,
        //        Settings = {
        //            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
        //            MaxDepth = 1// customer
        //                }
        //    };
        //    return result;
        //}


        //[HttpPost]
        //public ActionResult UpdateCurrentCustomer(
        //    string firstName
        //    , string lastName
        //    , string telephone
        //    , string email
        //    , string address)
        //{
        //    AnonymousUser customer = CheckCustomerId();

        //    customer.FirstName = firstName;
        //    customer.LastName = lastName;
        //    customer.PhoneNumber = telephone;
        //    customer.Email = email;
        //    customer.Address = address;


        //    db.Entry(customer).State = System.Data.Entity.EntityState.Modified;
        //    db.SaveChanges();

        //    return Json(
        //        new
        //        {
        //            success = true
        //        ,
        //            text = "cập nhật thông tin khách hàng thành công"
        //        }
        //    , JsonRequestBehavior.AllowGet);
        //}

        //#endregion


       // #region cart update

        /// <summary>
        /// add product into the cart
        /// </summary>
        /// <param name = "id" > product Id</param>
           // [HttpPost]
        //public ActionResult AddProduct(int id)
        //{
        //    ResultWeb result = new ResultWeb();
        //    Order cart = CheckOrderId();

        //    Product yourProduct = db.Products.Find(id);
        //    if (yourProduct == null)
        //    {
        //        result.Type = ResultWeb.ResultType.NOT_FOUND;
        //        return Json(new
        //        {
        //            success = false
        //        ,
        //            text = "Không tìm thấy sản phẩm này"
        //        }, JsonRequestBehavior.AllowGet);
        //    }

        //    var details = cart.OrderDetails;

        //    if (details == null)
        //    {
        //        details = new List<OrderDetail>();
        //    }

        //    OrderDetail yourDetail = details.Where(od => od.ProductId == id).FirstOrDefault();
        //    //trường hợp đã thêm sản phẩm này rồi, thêm nó vào lần nữa
        //    if (yourDetail != null)
        //    {
        //        if (yourProduct.InStock <= yourDetail.Quantity)
        //        {
        //            result.Type = ResultWeb.ResultType.OUT_OF_STOCK;
        //            return Json(new
        //            {
        //                success = false
        //        ,
        //                text = "Sản phẩm không đủ hàng"
        //            }, JsonRequestBehavior.AllowGet);
        //        }

        //        yourDetail.Quantity += 1;
        //        yourDetail.TotalAmount = yourDetail.Quantity * yourProduct.Price;
        //        db.Entry(yourDetail).State = System.Data.Entity.EntityState.Modified;
        //        db.SaveChanges();
        //    }
        //    else// trường hợp chưa có sản phẩm này, thêm vào giỏ
        //    {
        //        if (yourProduct.InStock <= 0)
        //        {
        //            result.Type = ResultWeb.ResultType.OUT_OF_STOCK;
        //            return Json(new
        //            {
        //                success = false
        //        ,
        //                text = "Sản phẩm không đủ hàng"
        //            }, JsonRequestBehavior.AllowGet);
        //        }

        //        yourDetail = new OrderDetail
        //        {
        //            OrderId = cart.ID,
        //            ProductId = yourProduct.ID,
        //            Quantity = 1,
        //            TotalAmount = yourProduct.Price
        //        };
        //        db.OrderDetails.Add(yourDetail);
        //        db.SaveChanges();

        //    }

        //    RecalculateOrderCost(cart);

        //    result.Type = ResultWeb.ResultType.OK;
        //    return Json(new
        //    {
        //        success = true
        //        ,
        //        text = "thêm sản phẩm vào giỏ thành công"
        //    }, JsonRequestBehavior.AllowGet);
        //}

        ///// <summary>
        ///// minus a product in the cart
        ///// </summary>
        ///// <param name = "id" > product id</param>
        //    [HttpPost]
        //public ActionResult MinusProduct(int id)
        //{
        //    ResultWeb result = new ResultWeb();
        //    Order cart = CheckOrderId();

        //    Product yourProduct = db.Products.Find(id);
        //    if (yourProduct == null)
        //    {
        //        result.Type = ResultWeb.ResultType.NOT_FOUND;
        //        return Json(new
        //        {
        //            success = false
        //        ,
        //            text = "Không tìm thấy sản phẩm"
        //        }, JsonRequestBehavior.AllowGet);
        //    }

        //    var details = cart.OrderDetails;

        //    if (details == null)
        //    {
        //        return Json(new
        //        {
        //            success = false
        //        ,
        //            text = "Không tìm thấy chi tiết giỏ hàng"
        //        }, JsonRequestBehavior.AllowGet);
        //    }

        //    OrderDetail yourDetail = details.Where(od => od.ProductId == id).FirstOrDefault();
        //    if (yourDetail != null)
        //    {
        //        if (yourDetail.Quantity < 0)
        //        {
        //            yourDetail.Quantity = 0;
        //            yourDetail.TotalAmount = 0;
        //            db.Entry(yourDetail).State = System.Data.Entity.EntityState.Modified;
        //            db.SaveChanges();

        //            RecalculateOrderCost(cart);

        //            result.Type = ResultWeb.ResultType.FIELD_INVALID;
        //            return Json(new
        //            {
        //                success = false
        //        ,
        //                text = "Lỗi chi tiết giỏ hàng không xác định"
        //            }, JsonRequestBehavior.AllowGet);
        //        }
        //        if (yourDetail.Quantity == 0)
        //        {
        //            result.Type = ResultWeb.ResultType.OK;
        //            return Json(new
        //            {
        //                success = false
        //        ,
        //                text = "Chi tiết giỏ hàng đã ở số nhỏ nhất"
        //            }, JsonRequestBehavior.AllowGet);
        //        }

        //        string resultText = "";
        //        bool theSuccess = false;
        //        if (yourProduct.InStock < yourDetail.Quantity - 1)
        //        {
        //            result.Type = ResultWeb.ResultType.OUT_OF_STOCK;
        //            theSuccess = false;
        //            resultText = "Lỗi số lượng chi tiết giỏ hàng";
        //            yourDetail.Quantity = yourProduct.InStock;
        //        }
        //        else
        //        {
        //            result.Type = ResultWeb.ResultType.OK;
        //            theSuccess = true;
        //            resultText = "Bớt sản phẩm thành công";
        //            yourDetail.Quantity -= 1;
        //        }

        //        yourDetail.TotalAmount = yourDetail.Quantity * yourProduct.Price;
        //        db.Entry(yourDetail).State = System.Data.Entity.EntityState.Modified;
        //        db.SaveChanges();

        //        RecalculateOrderCost(cart);

        //        return Json(new
        //        {
        //            success = theSuccess
        //        ,
        //            text = resultText
        //        }, JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        result.Type = ResultWeb.ResultType.FIELD_INVALID;
        //        return Json(new
        //        {

QuanLyBanSach-dbf/QuanLyBanSach-dbf/QuanLyBanSach/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyBanSach.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

QuanLyBanSach-dbf/QuanLyBanSach-dbf/QuanLyBanSach/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using QuanLyBanSach.Data;

namespace QuanLyBanSach.Controllers
{
    public class SearchController : Controller
    {
        BookStore db = new BookStore();

        // GET: Search
        public ActionResult Index(string key, int? costBegin, int? costEnd)
        {
            IQueryable<Product> products;
            if (!string.IsNullOrEmpty(key))
            {
                products = db.Products.Where(p => p.Name.Contains(key));
            }
            else
            {
                products = db.Products;
            }

            if (costBegin != null)
            {
                products = products.Where(p => p.CostPrice >= costBegin);
            }
            if (costEnd != null)
            {
                products = products.Where(p => p.CostPrice <= costEnd);
            }

            ViewData["Categories"] = db.Categories.ToList();
            ViewData["Authors"] = db.Authors.ToList();
            return View(products.ToList());
        }

        //    /// <summary>
        //    /// As same as the view above, but this only return json
        //    /// </summary>
        [HttpGet]
        public ActionResult Search(
            string key
            , int? authorId, int? categoryId
            , int? costBegin, int? costEnd)
        {
            if (costBegin != null)
            {
                costBegin *= 1000;
            }
            if (costEnd != null)
            {
                costEnd *= 1000;
            }
            List<Product> products;
            if (!string.IsNullOrEmpty(key))
            {
                products = db.Products.Where(p => p.Name.Contains(key)).ToList();
            }
            else
            {
                products = db.Products.ToList();
            }

            if (authorId != null)
            {
                //List<Product> tmp = products.ToList();
                //List<Product> tmp2 = new List<Product>(tmp);
                //foreach (var singleProduct in tmp2)
                //{
                //    var details = singleProduct.ProductDetails;
                //    if (details != null)
                //    {
                //        var found = details.Where(pd => pd.AuthorId == authorId);
                //        if (found == null || found.Count() == 0)
                //        {
                //            tmp.Remove(singleProduct);
                //        }
                //    }
                //}
                //if (tmp.Count == 0)
                //    return Json(tmp, JsonRequestBehavior.AllowGet);

                try
                {
                    //products = tmp.AsQueryable();
                    products = db.sp_FilterByAuthorID(authorId).ToList();
                }
                catch (Exception)
                {
                    return Json("Error at tmp.AsQueryable()", JsonRequestBehavior.AllowGet);
                }

            }

            if (categoryId != null)
            {
                products = products.Where(p => p.CategoryId == categoryId).ToList();

                if (products.Count() == 0)
                    return Json(new List<Product>(), JsonRequestBehavior.AllowGet);
            }

            if (costBegin != null)
            {
                products = products.Where(p => p.Price >= costBegin).ToList();
                if (products.Count() == 0)
                    return Json(new List<Product>(), JsonRequestBehavior.AllowGet);
            }
            if (costEnd != null)
            {
                products = products.Where(p => p.Price <= costEnd).ToList();
                if (products.Count() == 0)
                    return Json(new List<Product>(), JsonRequestBehavior.AllowGet);
            }

            var result = new JsonNetResult
            {
                Data = products.ToList(),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                Settings = {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                MaxDepth = 3// product, productdetail, author
                    }
            };
            return result;
        }
    }


}

QuanLyBanSach-dbf/QuanLyBanSach-dbf/QuanLyBanSach/Views/Shared/Header.cshtml
<head>
    <link href="~/Content/css/Header.css" rel="stylesheet">
</head>
<header id="header">
    <!--header-->
    <div class="header-bottom sticky-navbar">
        <!--header-bottom-->
        <div class="container logo-container">

        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-1">
                    <a href=@Url.Action("Index", "Home")>
                        <img src="~/Content/images/home/logo.png" style="width:100px;height:40px
" />
                    </a>
                </div>
                <div class="col-lg-3">
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            @*<li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>*@
                            <li>@Html.ActionLink("Sản phẩm", "Index", "Search")</li>
                            <li>@Html.ActionLink("Liên hệ", "Index", "Contact")</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="search_box">
                        <input id="search_box" type="search" placeholder="Tìm kiếm"
                               onkeypress="onKeypressSearch(event)" />
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="shop-menu pull-left">
                        <ul class="nav navbar-nav">
                            <li class="dropdown-cart">
                                <a class="dropbtn shopping-cart" href=@Url.Action("Index", "Cart")>
                                    <img src="~/Content/images/home/shopping-cart.png" style="width:35px;height:35px" /> GIỎ HÀNG <span class="badge badge-light" style="width:20px;height:20px">4</span>
                                </a>

                                @*<div class="dropdown-content">
                                    <table class="table table-fixed-preview">
                                        <thead>
                                            <tr class="cart_menu">
                                                <th class="description col-xs-5">Sản phẩm</th>
                                                <th class="price col-xs-1" style="text-align:center">Giá</th>
                                                <th class="quantity col-xs-3" style="margin-left:10px">Số lượng</th>
                                                <th class="total col-xs-2">Tổng</th>
                                            </tr>
                                        </thead>
                                        <tbody class="cart-body-prv"></tbody>
                                    </table>
                                </div>*@
                            <li>
                                <a class="login-button" href=@Url.Action("Login", "Staff")>
                                    <img src="~/Content/images/home/login.png" style="width:32px;height:32px" />USER
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <div class="container logo-container">

        </div>

    </div><!--/header-bottom-->
</header><!--/header-->

@*<script src="~/Content/js/jquery.js" type="text/javascript"></script>*@


<script>
    $(document).ready(function () {
        //getCart("preview");
    })

    function getCart(viewType) {
        $.ajax({
            url: '/Cart/GetCart',
            type: 'GET',
            dataType: 'json',
            data: { "id": null },
            success: function (data) {
                populateOrderDetails(data.OrderDetails, viewType);
            },
            error: function (err) {
                alert(err.responseJSON);
                document.write(err.responseText);
            }
        })
    }

    function populateOrderDetails(data, viewType) {
        var rows = '';
        var iurl;
        if (viewType == "preview") {
            $.each(data, function (i, item) {

                if (item.Product.AvatarImage) {
                    iurl = item.Product.AvatarImage.replace("~", "");
                }
                else {
                    iurl = "/Content/images/home/default-image.png"
                }
                if (item.Quantity == 0) {
                    return true;
                }
                rows += '<tr style="height:57px">'
                rows += '                                 <td class="cart_description col-xs-5"> <img style="vertical-align:middle;float:left;max-height:50px;max-width:50px;object-fit:contain;margin-right:4px" onerror="' + "if (this.src != '/Content/images/home/default-image.png') this.src = '/Content/images/home/default-image.png';" + '" src="' + iurl + '" width="40px" height="40px"></a>'
                rows += '                                     <h4 style="margin:0"><a href="/Products/Single?id=' + item.Product.ID + '" class="shorten-name" style="background-color:transparent;color:#0fb3bc; font-weight:bold;white-space: pre-wrap;margin:0">' + item.Product.Name + '</a></h4>'
                rows += '                                   </td>'
                rows += '                                   <td class="cart_price col-xs-1" style="line-height:57px;padding:0">'
                rows += '                                       <p style="margin:0;text-align:center" >' + (item.Product.Price / 1000).toLocaleString() + 'k</p>'
                rows += '                                   </td>'
                rows += '                                  <td class="cart_quantity col-xs-3" style="margin-right:-10px">'
                rows += '                                     <div class="cart_quantity_button"> <p hidden>' + item.ProductId + '</p>'
                rows += '                                        <a style="height:20px" class="cart_quantity_up" href="">+</a>'
                rows += '                                       <input style="height:28px" class="cart_quantity_input_prv" type="text" name="quantity" readonly value="' + item.Quantity + '" autocomplete="off" size="2">'
                rows += '                                      <a style="height:20px" class="cart_quantity_down" href="">-</a>'
                rows += '                                 </div>'
                rows += '                            </td>'
                rows += '                           <td class="cart_total col-xs-2" style="line-height:57px;padding:0">'
                rows += '                              <p style="margin:0;text-align:center" class="cart_total_price">' + (item.TotalAmount / 1000).toLocaleString() + 'k</p>'
                rows += '                         </td>'
                rows += '                        <td class="cart_delete" style="padding-right:0"><p hidden>' + item.ProductId + '</p>'
                rows += '                           <a class="cart_quantity_delete" style="background-color:transparent" href=""><i class="fa fa-times"></i></a>'
                rows += '                      </td>'
                rows += '                 </tr>';
            });
            $(".cart-body-prv").html(rows);
        }
        else if (viewType == "main") {
            $.each(data, function (i, item) {
                if (item.Product.AvatarImage) {
                    iurl = item.Product.AvatarImage.replace("~", "");
                }
                else {
                    iurl = "/Content/images/home/default-image.png"
                }
                if (item.Quantity == 0) {
                    return true;
                }
                rows += '<tr>'
                rows += '              <td class="cart_description col-lg-5"> <a href="/Products/Single?id=' + item.Product.ID + '"><img style="float:left" onerror="' + "if (this.src != '/Content/images/home/default-image.png') this.src = '/Content/images/home/default-image.png';" + '" src="' + iurl + '" width="60px" height="60px"></a>'
                rows += '                  <h4><a style="margin-left:5px" href="/Products/Single?id=' + item.Product.ID + '">' + item.Product.Name + '</a></h4>'
                rows += '             <p><text style="margin-left:5px">Mã hàng: ' + item.Product.ID + '</text></p>'
                rows += '         </td>'
                rows += '         <td class="cart_price col-lg-2" style="text-align:center">'
                rows += '             <p style="margin:0">' + (item.Product.Price / 1000).toLocaleString() + 'k</p>'
                rows += '         </td>'
                rows += '         <td class="cart_quantity col-lg-2">'
                rows += '             <div class="cart_quantity_button"> <p hidden>' + item.ProductId + '</p>'
                rows += '                 <a style="height:23px" class="cart_quantity_up" href="">+</a>'
                rows += '                 <input style="height:23px" class="cart_quantity_input" type="text" name="quantity" readonly value="' + item.Quantity + '" autocomplete="off" size="2">'
                rows += '                 <a style="height:23px" class="cart_quantity_down" href="">-</a>'
                rows += '             </div>'
                rows += '         </td>'
                rows += '         <td class="cart_total col-lg-2" style="text-align:center">'
                rows += '             <p style="margin:0" class="cart_total_price">' + (item.TotalAmount / 1000).toLocaleString() + 'k</p>'
                rows += '         </td>'
                rows += '         <td class="cart_delete"> <p hidden>' + item.ProductId + '</p>'
                rows += '             <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>'
                rows += '         </td>'
                rows += '     </tr>'
            });
            $(".cart-body").html(rows);
        }

    }
    $(".cart-body-prv").on("click", "tr>td>div>.cart_quantity_up", function (event) {
        event.preventDefault();
        var productID = $(this).parent().children('p').text();
        updateCart("add", productID, event)
    });

    $(".cart-body-prv").on("click", "tr>td>div>.cart_quantity_down", function (event) {
        event.preventDefault();
        var productID = $(this).parent().children('p').text();
        updateCart("minus", productID, event)
    });

    $(".cart-body-prv").on("click", "tr>td>.cart_quantity_delete", function (event) {
        event.preventDefault();
        var productID = $(this).parent().children('p').text();
        updateCart("delete", productID, event)
    });


    function updateCart(action, productID, event) {
        event.preventDefault();
        var actionurl = ''

        switch (action) {
            case "add":
                actionurl = '/Cart/AddProduct'
                break;
            case "minus":
                actionurl = '/Cart/MinusProduct'
                break;
            case "delete":
                actionurl = '/Cart/DeleteProduct'
                break;
        }

        $.ajax({
            url: actionurl,
            type: 'POST',
            dataType: 'json',
            data: { "id": productID },
            success: function (data) {

                if (!data.success) {
                    alert(data.text);
                }

                getCart("preview");
                getCart("main");
            },
            error: function (err) {
                alert(err.responseJSON);
                document.write(err.responseText);
            }
        })

    }


    @*$("#search_box").click(function () {

        var currentpage = '@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()'
        if (currentpage != 'Search') {
            window.location.href = '@Url.Action("Index","Search")'
        }

    });*@
    function onKeypressSearch(e) {
        var keynum;

        if (window.event) { // IE
            keynum = e.keyCode;
        } else if (e.which) { // Netscape/Firefox/Opera
            keynum = e.which;
        }

        if (keynum == 13) {
            onSearch();
        }
    }

</script>

QuanLyBanSach-dbf/QuanLyBanSach-dbf/QuanLyBanSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/libs/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/css/libs/Site.css" rel="stylesheet">
    <link href="~/Content/css/libs/responsive.css" rel="stylesheet">
</head><!--/head-->
<body>
    @Html.Partial("Header")
    <div style="margin-top:100px;">
        @RenderBody()
    </div>
    @Html.Partial("Footer")
    <script src="~/Content/js/bootstrap/bootstrap.min.js"></script>
    <script src="~/Content/js/jquery/jquery.scrollUp.min.js"></script>
    <script src="~/Content/js/jquery/jquery.prettyPhoto.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script src="~/Content/js/others/moment.js" type="text/javascript"></script>
    <script src="~/Content/js/helper.js" type="text/javascript"></script>
    <script src="~/Content/js/functions.js" type="text/javascript"></script>
</body>
</html>